name: NodeJS

on:
  # push:
    # branches:
     # - master
  workflow_dispatch:

jobs:
  nodejs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Pre Deployment Deploy
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            rm -rf nodejs-deploy
    - name: Install Dependencies
      run: npm install
      # Deploy the artifact into  instance
    - name: Nodejs app Deploy
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: nodejs-deploy
      # Post deployment
    - name: Post Deploy
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # pm2 start --name=app npm -- start
            pm2 restart app
              
              
